CREATE TABLE categories (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  category VARCHAR(50),
  PRIMARY KEY (id),
  FOREIGN KEY (id) REFERENCES ads(id)

);

CREATE TABLE adCategories (
  id  INT UNSIGNED NOT NULL AUTO_INCREMENT,
  ad_id INT UNSIGNED NOT NULL,
  cat_id INT UNSIGNED NOT NULL,
  FOREIGN KEY (ad_id) REFERENCES ads(id),
  FOREIGN KEY (cat_id) REFERENCES categories(id),
  PRIMARY KEY (id)
)